---
title: "Proximity sensor testing"
output: html_notebook
---


```{r}
library(tidyverse)
library(readr)
library(lubridate)
```

Goals: 
1. see the number of reads from each tag
2. tag each meeting by pairwise distance
     --- convert times into datetimes? 
     --- if datetime  between X and X, joinby?  
3. compare rssi by distance




```{r}


#test_table <- read.csv("https://raw.githubusercontent.com/maydixon/proximity-sensors/main/test_table.csv", sep=",", header=TRUE ) #stringsAsFactors = F
test_table <- read_csv("test_table.csv")

View(test_table)

# MN_DATA_nov7_2 <- read.csv("https://raw.githubusercontent.com/maydixon/proximity-sensors/blob/main/23-11-08/15-51-42/MN_DATA.CSV",sep=",", header=TRUE, stringsAsFactors = F )
# for some reason reading in with a lagging line

MN_DATA <- read_csv("23-11-08/15-51-42/MN_DATA.CSV")
View(MN_DATA)

str(d)     
```


```{r}
colnames(MN_DATA) 

#remove spaces from MN_DATA column names
colnames(MN_DATA) <- sub(" ", "_", colnames(MN_DATA))

#put date time in one column for MN_DATA
MN_DATA <- MN_DATA %>%
       mutate(date_time = make_datetime(year = Meeting_Year, month = Meeting_Month, day = Meeting_Day, hour = Meeting_Hour,min =  Meeting_Minute, sec = Meeting_Second)) 

# put date time in two columns for test table
test_table <- test_table %>%
      mutate(start_time = make_datetime(year = start_year, month = start_month, day = start_day, hour = start_hour, min =  start_minute, sec = start_second), 
             end_time = make_datetime(year = end_year, month = end_month, day = end_day, hour = end_hour, min =  end_minute, sec = end_second))

```
if mn_data date_time  is between test_table start_time and end_time


Number of reads of each tag

```{r}
#number of meetings transmitted by each tag
TX_sum <- MN_DATA %>%
      group_by(TX_Node) %>%
      summarise(n=n())
TX_sum

TX_sum_p <- ggplot(MN_DATA, aes(x= as.factor(TX_Node))) +
      geom_bar()
TX_sum_p

```
```{r}
#number of meetings transmitted by each tag
RX_sum <- MN_DATA %>%
      group_by(RX_Node) %>%
      summarise(n=n())
RX_sum

RX_sum_p <- ggplot(MN_DATA, aes(x= as.factor(RX_Node))) +
      geom_bar()
RX_sum_p

#90 didn't even transmit anything
```


```{r}
lubridate?
talk with elizabeth

```

